name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sync version from release tag
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          npm version "$VERSION" --no-git-tag-version --allow-same-version

      - name: Install Dependencies
        run: npm install

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm run prepare-dist
          cd dist
          npm install --omit=dev
          cd ..
          npx electron-builder --win --config electron-builder.config.js -p never

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: |
          npm run prepare-dist
          cd dist
          npm install --omit=dev
          cd ..
          npx electron-builder --mac --config electron-builder.config.js -p never

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools
          npm run prepare-dist
          cd dist
          npm install --omit=dev
          cd ..
          npx electron-builder --linux --config electron-builder.config.js -p never

      - name: Upload artifacts to release
        shell: bash
        run: gh release upload "$GITHUB_REF_NAME" release/*.*  --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
